[package]
name = "reverseProxy"
version = "0.1.0"
authors = ["Zachary Metz <zachary.metz@ucalgary.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "^0.2"
base64 = "0.11.0"
json = "0.12.1"
